<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MajorMiseries</RootNamespace>
		<AssemblyName>MajorMiseries</AssemblyName>
		<LangVersion>latest</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.1.1.0</AssemblyVersion>
		<FileVersion>1.1.1.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<Platforms>AnyCPU;x64</Platforms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup>
		<TheLongDarkPath>D:\SteamLibrary\steamapps\common\TheLongDark</TheLongDarkPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\Icons\Afflictions\Classic\AuroraExposure.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\BlackLung.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\BrokenArm.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\BrokenLeg.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\COExposure.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\COPoisoning.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\CorpseSickness.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\Dirge.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\Fever.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\HomeSickness.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\Knell.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\Omen.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\RegionalDistress.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\Requiem.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\ScarredFlesh.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\Sepsis.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\SevereAnkleSprain_Left.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\SevereAnkleSprain_Right.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\SevereWristSprain_Left.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\SevereWristSprain_Right.png" />
	  <None Remove="Resources\Icons\Afflictions\Classic\VoidSickness.png" />
	  <None Remove="Resources\Icons\Aperture.png" />
	  <None Remove="Resources\Icons\Buffs\Classic\HomeComfort.png" />
	  <None Remove="Resources\Localization\Localization.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\AuroraExposure.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\BlackLung.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\BrokenArm.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\BrokenLeg.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\COExposure.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\COPoisoning.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\CorpseSickness.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Dirge.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Fever.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\HomeSickness.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Knell.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Omen.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\RegionalDistress.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Requiem.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\ScarredFlesh.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Sepsis.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SevereAnkleSprain_Left.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SevereAnkleSprain_Right.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SevereWristSprain_Left.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SevereWristSprain_Right.png" />
	  <EmbeddedResource Include="Resources\Icons\Afflictions\Classic\VoidSickness.png" />
	  <EmbeddedResource Include="Resources\Icons\Buffs\Classic\HomeComfort.png" />
	  <EmbeddedResource Include="Resources\Localization\Localization.json" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="AfflictionComponent">
			<HintPath>$(TheLongDarkPath)\Mods\AfflictionComponent.dll</HintPath>
		</Reference>
		<Reference Include="ModSettings">
			<HintPath>$(TheLongDarkPath)\Mods\ModSettings.dll</HintPath>
		</Reference>
		<Reference Include="ModComponent">
			<HintPath>$(TheLongDarkPath)\Mods\ModComponent.dll</HintPath>
		</Reference>
		<Reference Include="ModData">
			<HintPath>$(TheLongDarkPath)\Mods\ModData.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
		<PackageReference Include="Waltz.Modding.TLD.Il2CppAssemblies.Windows" Version="2.52.0" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
		<Using Include="ModSettings" />
		<Using Include="ModComponent" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)\Mods" SkipUnchangedFiles="true" />
	</Target>
</Project>